# Generated by Django 3.2.3 on 2022-09-20 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0002_queue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queue',
            name='added_on',
            field=models.DateTimeField(null=True),
        ),
    ]
