# Generated by Django 3.2.3 on 2022-09-24 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0003_alter_queue_added_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='queue',
            name='votes',
        ),
        migrations.AlterField(
            model_name='queue',
            name='tracks',
            field=models.JSONField(default={'tracks': []}),
        ),
    ]
