# Generated by Django 3.2.3 on 2022-09-13 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20220912_1831'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='photoURL',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
