# Generated by Django 3.2.3 on 2022-09-24 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_users_photourl'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='guests',
            field=models.JSONField(default={'guests': []}),
        ),
    ]
